stream_sizes: [1]
has_dynamic_features: [false]
stream_weights: [1]

netG:
  _target_: nnsvs.model.VariancePredictor
  in_dim: 278
  out_dim: 1
  hidden_dim: 256
  num_layers: 2
  kernel_size: 3
  dropout: 0.6
  use_mdn: true
  num_gaussians: 4
  init_type: "kaiming_normal"
